reports:
  - name: Heading accessibility
    filename: heading_ordering_report_generator.py
    class: HeadingOrderingReportGenerator
    skip: true
  - name: Non-English docs
    filename: non_english_docs_report_generator.py
    class: NonEnglishDocsReportGenerator
    skip: true
  - name: Tables
    filename: tables_report_generator.py
    class: TablesReportGenerator
    skip: true
  - name: Links that have same text but different URLs
    filename: link_text_report_generator.py
    class: LinkTextReportGenerator
    skip: true
  - name: Find pages with non-HTML attachments
    filename: non_html_attachment_report_generator.py
    class: NonHtmlAttachmentReportGenerator
    skip: true
  - name: Find pages with headers that are being represented as bold text
    filename: fake_header_report_generator.py
    class: FakeHeaderReportGenerator
    skip: true
  - name: Entities for all content
    filename: entity_report_generator.py
    class: EntityReportGenerator
    skip: false

settings:
  turbo_mode: true
  html_content_dir_path: /Users/oscarwyatt/govuk/govuk-knowledge-extractor/govuk-production-mirror-replica
  preprocessed_content_store_path: /Users/oscarwyatt/govuk/govuk-knowledge-graph/data/preprocessed_content_store_070920.csv.gz
  total_content_items: 1000000
  content_item_batch_size: 8
  csv_writer_buffer_size: 32
